library(dplyr)
mechacar <- read.csv(file='MechaCar_mpg.csv')
mechacarDF <- as.data.frame(mechacar)
summary(mechacarDF)
mpg_eval <- lm(mpg ~ ., data = mechacarDF)
AWD_eval <- lm(AWD ~., data = mechacarDF)
length_eval <- lm(vehicle_length ~ ., data = mechacarDF)
weight_eval <- lm(vehicle_weight ~ ., data = mechacarDF)
spoiler_eval <- lm(spoiler_angle ~ ., data = mechacarDF)
clearance_eval <- lm(ground_clearance ~ ., data = mechacarDF)
summary(mpg_eval)
summary(AWD_eval)
summary(length_eval)
summary(weight_eval)
summary(spoiler_eval)
summary(clearance_eval)
